name: decimal_mask CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: python:3.10

    steps:
    - uses: actions/checkout@v3
    - uses: abatilo/actions-poetry@v2.2.0
      with:
        poetry-version: 1.3.0
    - name: Test with Django
      run: |
        poetry install
        poetry run pytest --migrations
